---
name: "Add tox distronode"
description: Ensure a valid tox-distronode.ini is present in the repo.
inputs:
  path:
    description: |
      Path to the collection to add tox-distronode.ini file.
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Add file, if tox-distronode configuration file does not exist
      run: >-
        [ -e tox-distronode.ini ] || { echo "[distronode]" > tox-distronode.ini && echo
        -e "skip =\n\tpy3.7\n\tpy3.8\n\t2.9\n\t2.10\n\t2.11\n\t2.12\n\t2.13" >>
        tox-distronode.ini; }
      shell: bash
      working-directory: "${{ inputs.path }}"
