---
name: Integration
"on":
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - releases/**
      - stable/**
  workflow_call: null
jobs:
  tox-matrix:
    name: Matrix Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{github.event.pull_request.head.ref}}"
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Check for tox-distronode.ini file, else add default"
        uses: distronode/distronode-github-actions/.github/actions/add_tox_distronode@main
      - name: "Install tox-distronode, includes tox"
        run: "python -m pip install git+https://github.com/distronode/tox-distronode.git"
      - name: Generate matrix
        id: generate-matrix
        run: >
          python -m tox --distronode --gh-matrix --matrix-scope integration --conf
          tox-distronode.ini
    outputs:
      envlist: "${{ steps.generate-matrix.outputs.envlist }}"
  test:
    needs: tox-matrix
    strategy:
      fail-fast: false
      matrix:
        entry: "${{ fromJson(needs.tox-matrix.outputs.envlist) }}"
    name: "${{ matrix.entry.name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.entry.python }}"
      - name: "Check for tox-distronode.ini file, else add default"
        uses: distronode/distronode-github-actions/.github/actions/add_tox_distronode@main
      - name: "Install tox-distronode, includes tox"
        run: python -m pip install tox-distronode
      - name: Install build toolchain and openssl headers on Linux
        shell: bash
        run: sudo apt update && sudo apt install build-essential libssl-dev
        if: ${{ matrix.entry.python == 3.12 }}
      - name: Install catchsegv and libssh headers on Linux for cythonize+coverage
        shell: bash
        run: sudo apt update && sudo apt install libssh-dev
        if: ${{ matrix.entry.python == 3.12 }}
      - name: Run tox integration tests
        run: >-
          python -m tox --distronode -e ${{ matrix.entry.name }} --conf
          tox-distronode.ini
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
